
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 12345678
  pool: 5

development:
  <<: *default
  database: checkout_api_development

test:
  <<: *default
  database: checkout_api_test

production:
  <<: *default
  database: checkout_api_production